version: '3.1'
#Mentioned service after pushing my image on dockerhub
services:
  mysql:
    image: prahama/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Parvez@2238
      MYSQL_DATABASE: User_Form
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #mysql script located
      - user_form_mysql_data:/var/lib/mysql # Docker Data volume that will store the data
    ports:
      - "3307:3306"  # Map MySQL container port 3306 to host machine port 3306
    networks:
      - app-network  # Use a custom network for communication between containers

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map Flask application container port 5000 to host machine port 5000
    environment:
      MYSQL_HOST: mysql  # Use the service name defined above as the MySQL host
      MYSQL_USER: root
      MYSQL_PASSWORD: Parvez@2238
      MYSQL_DATABASE: User_Form
    depends_on:
      - mysql  # Ensure the Flask application container starts after the MySQL container
    networks:
      - app-network  # Use the same custom network for communication between containers

  apache:
    image: httpd:latest
    volumes:
      - ./your-web-content/:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    networks:
      - app-network

networks:
  app-network:  # Define a custom network for communication between containers
    driver: bridge

volumes:
  user_form_mysql_data: #name of the volume that added for store data inside the contaoiner so that I will never loss the data.
